:set number
:set relativenumber
:colorscheme slate
:set cursorline " enable line highlight, then define colors
:hi CursorLine cterm=NONE ctermbg=darkblue ctermfg=yellow " ctermbg - background color, ctermfg - text color

call plug#begin('~/.vim/plugged')
Plug 'https://github.com/preservim/nerdtree' " NerdTree
Plug 'https://github.com/vim-airline/vim-airline' " Status bar
call plug#end()


nnoremap <C-n> :NERDTree<CR>
